name: ligo
channels:
   - conda-forge
   - defaults
dependencies:
   - python=3.12
   - numpy=1.26
   - decorator=5.1
   - scipy=1.15
   - matplotlib=3.9
   - h5py=3.12
   - jupyterlab=4.2
   - ipykernel=6.29 
   
